/**
 * Every user-facing string in the product. One module so a second language is a second object,
 * not an excavation through components (spec §2.5).
 */
export const UI = {
  nav: { create: "Create token", search: "Search tokens", admin: "Admin", discover: "Discover", watchlist: "Watchlist", positions: "Positions", profile: "Profile", main: "Main" },
  // Named after the chain it is on, so a second testnet never says "SEPOLIA".
  badge: { testnet: (chainName: string) => `${chainName.toUpperCase()} TESTNET` },
  create: {
    title: "Create a token",
    intro: "Launch a token on a bonding curve. It costs a small creation fee plus network fees, and you can start trading it straight away.",
    fields: {
      name: "Name",
      ticker: "Ticker",
      description: "Description",
      image: "Logo",
      imageHint: "PNG, JPEG or WebP, up to 2 MB.",
      website: "Website",
      twitter: "Twitter",
      telegram: "Telegram",
      optional: "optional",
    },
    errors: {
      name: "Enter a name of 1 to 32 characters.",
      ticker: "Use 2 to 10 letters or digits, with no spaces.",
      description: "Keep the description to 500 characters.",
      link: "Enter a link that starts with http:// or https://.",
      image: "Choose a PNG, JPEG or WebP image of 2 MB or less.",
      imageMissing: "Choose a logo.",
    },
    window: {
      title: "Launch protection",
      help: "For the first minutes after launch a tax is charged on every buy, so bots cannot take the cheapest tokens. It falls to zero by the end of the window.",
      warning: "You pay the launch tax too, on your own buys.",
      options: { 0: "No protection", 60: "60 seconds", 600: "10 minutes", 5880: "98 minutes" },
    },
    cost: {
      fee: "Creation fee",
      gas: "Estimated network fee",
      note: "Shown before your wallet opens. The creation fee is refunded in full if the transaction fails.",
    },
    submit: "Create token",
    signInFirst: "Sign in with your wallet to upload the logo.",
    steps: { label: "Progress", upload: "Upload details", confirm: "Confirm in your wallet", live: "Token live" },
    failed: "Could not create the token.",
  },
  discover: {
    tabs: { new: "New", trending: "Trending", progress: "Nearing graduation" },
    view: { label: "View", table: "Table", grid: "Grid" },
    empty: "No tokens yet. Be the first to create one.",
    searchEmpty: "No tokens match that search.",
    next: "Next page",
  },
  positions: {
    title: "Positions",
    intro: "What you hold, what it cost and what it is worth, and every order you have made.",
    tabs: { label: "Positions views", positions: "Positions", orders: "Order history" },
    connect: "Connect a wallet to see your positions and orders.",
    connectButton: "Log in",
    loading: "Loading…",
    emptyPositions: "You hold no tokens yet. Buy one and it will show here.",
    emptyOrders: "You have not placed an order yet.",
    columns: { token: "Token", balance: "Balance", value: "Value", bought: "Bought", sold: "Sold", pnl: "PnL", action: "Trade", time: "Time", type: "Type", total: "Total", amount: "Amount", price: "Price", tx: "Transaction" },
    totals: { value: "Total value", pnl: "Total PnL" },
    viewTx: "View",
    loadMore: "Load more",
  },
  watchlist: {
    title: "Watchlist",
    intro: "The tokens you have starred.",
    empty: "No starred tokens yet. Press the star beside a token to keep it here.",
    loggedOut: "Log in to see the tokens you have starred.",
    login: "Log in",
    signIn: "Sign in",
    loading: "Loading your watchlist…",
  },
  favorites: {
    star: (name: string) => `Star ${name}`,
    errors: {
      tooMany: "You can star at most 500 tokens. Remove one first.",
      rateLimited: "You are changing your stars too fast. Please wait a moment.",
      network: "Could not reach the server. Your star was not saved.",
      signedOut: "Log in to star tokens.",
      signIn: "Could not sign you in. Please try again.",
      generic: "Could not save your star. Please try again.",
    },
  },
  token: {
    status: { trading: "TRADING", graduating: "GRADUATING…", graduated: "GRADUATED" },
    progress: "Graduation progress",
    collected: (have: string, target: string, symbol: string) => `${have} / ${target} ${symbol} collected`,
    tabs: { trades: "Trades", holders: "Holders", comments: "Comments" },
    tradeOnUniswap: "Trade on Uniswap",
    launchTaxBanner: (multiplier: string, countdown: string) =>
      `Launch protection is on: buying now costs ${multiplier}× the normal price. It ends in ${countdown}.`,
    launchTaxDialog: {
      title: "Launch tax is active",
      body: (percent: string, multiplier: string) =>
        `A ${percent} launch tax applies to buys right now, so this purchase costs ${multiplier}× the normal price. The tax falls every second until the window ends. Waiting is cheaper.`,
      confirm: "Buy anyway",
      cancel: "Cancel",
    },
    creator: "creator",
    marketCap: "mcap",
    price: "price",
    trades: (n: number) => `${n} ${n === 1 ? "trade" : "trades"}`,
    side: { buy: "Buy", sell: "Sell" },
    columns: {
      rank: "#",
      type: "Type",
      amount: "Amount",
      value: "Value",
      trader: "Trader",
      time: "Time",
      holder: "Holder",
      balance: "Balance",
      share: "Share",
    },
    noTrades: "No trades yet.",
    noHolders: "No holders yet.",
  },
  comments: {
    empty: "No comments yet. Be the first to say something.",
    label: "Comment",
    placeholder: "Write a comment",
    submit: "Post",
    posting: "Posting…",
    counter: (used: number, max: number) => `${used} / ${max}`,
    connectPrompt: "Connect a wallet to join the conversation.",
    signInPrompt: "Sign in to join the conversation.",
    signIn: "Sign in",
    loadMore: "Show older comments",
    anonymous: "unknown",
    errors: {
      banned: "You cannot post here.",
      rateLimited: "You are commenting too fast. Please wait a moment.",
      tooLong: "That comment is too long.",
      hiddenToken: "This token is no longer available.",
      network: "Could not reach the server. Your comment is still in the box.",
      generic: "Could not post your comment. Please try again.",
    },
  },
  fund: {
    title: "Add ETH to get started",
    body: (symbol: string) => `This wallet holds no ${symbol}, and nothing can be bought until it does. Send some to this address:`,
    copy: "Copy address",
    copied: "Copied",
    faucet: "Get free testnet ETH from a faucet",
    addFirst: "Add ETH first",
  },
  moderation: {
    hideToken: "Hide token",
    hideComment: "Hide",
    hideTokenTitle: "Hide this token?",
    hideTokenBody: "It disappears for everyone at once: from lists, from search and from its own page. Nothing is deleted, and it can be shown again.",
    hideCommentTitle: "Hide this comment?",
    hideCommentBody: "It disappears for everyone at once. Nothing is deleted.",
    confirm: "Hide",
    hiding: "Hiding…",
    cancel: "Cancel",
    report: "Report",
    reportTitle: "Report this token",
    reportBody: "Tell the moderators what is wrong with it. They will look at it.",
    reportLabel: "What is wrong?",
    reportSubmit: "Send report",
    reportSending: "Sending…",
    reportThanks: "Thank you. A moderator will look at it.",
    reportAlready: "You have already reported this token. A moderator will look at it.",
    reportClose: "Close",
    errors: {
      notFound: "That is no longer there.",
      rateLimited: "You are doing that too fast. Please try again later.",
      network: "Could not reach the server. Please try again.",
      generic: "That did not work. Please try again.",
    },
  },
  admin: {
    title: "Admin",
    health: {
      title: "System health",
      indexer: "Indexer",
      inSync: "In sync",
      behind: (blocks: number) => `${blocks} ${blocks === 1 ? "block" : "blocks"} behind`,
      watcher: "Watcher",
      running: (since: string) => `Running, started ${since}`,
      notRunning: "Not running",
      bot: "Bot wallet",
      failedMetadata: "Failed metadata",
      none: "None",
      retry: "Retry all",
      retrying: "Retrying…",
      retried: (n: number) => `${n} ${n === 1 ? "token" : "tokens"} will be resolved again.`,
      unknown: "Unknown",
    },
    stuck: {
      title: "Curves waiting to migrate",
      empty: "Nothing is waiting.",
      since: (age: string) => `full ${age}`,
      migrate: "Migrate",
      migrating: "Migrating…",
      migrated: "Migrated.",
      help: "Any wallet may finish a curve that has filled. This sends the transaction from yours.",
    },
    reports: {
      title: "Reports",
      empty: "No open reports.",
      hidden: "hidden",
      dismiss: "Dismiss",
      dismissing: "Dismissing…",
      by: "reported by",
    },
    ban: {
      title: "Ban an address",
      label: "Address",
      button: "Ban address",
      dialogTitle: "Ban this address?",
      dialogBody: "Their comments stop being shown everywhere and they cannot post again. Nothing is deleted.",
      confirm: "Ban",
      confirming: "Banning…",
      done: "Banned.",
      unban: {
        button: "Unban address",
        dialogTitle: "Let this address post again?",
        dialogBody: "Their comments are shown again, except any a moderator hid by hand, and they can post.",
        confirm: "Unban",
        confirming: "Unbanning…",
        done: "Ban lifted.",
      },
    },
    loadFailed: "Could not load this section.",
  },
  profile: {
    tabs: { created: "Created", holdings: "Holdings" },
    noCreated: "Nothing created yet.",
    noHoldings: "Nothing held yet.",
    balance: (amount: string, ticker: string) => `${amount} ${ticker}`,
    mainWallet: "Main wallet",
    sessionWallet: "Trading wallet",
    fees: {
      title: "Creator fees",
      available: (amount: string, symbol: string) => `${amount} ${symbol} is waiting for you.`,
      claim: "Claim creator fees",
      claiming: "Claiming…",
      claimed: "Claimed.",
    },
    edit: {
      button: "Edit profile",
      title: "Edit your profile",
      usernameLabel: "Username",
      usernameHelp: "3 to 20 letters, digits or underscores. Leave it empty to have none.",
      avatarLabel: "Picture",
      avatarHelp: "PNG, JPEG or WebP, up to 2 MB.",
      removeAvatar: "Remove my picture",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      errors: {
        usernameTaken: "That username is taken.",
        badUsername: "Use 3 to 20 letters, digits or underscores, and not something that looks like an address.",
        badImage: "That picture could not be used. Choose a PNG, JPEG or WebP image.",
        imageTooBig: "That picture is over 2 MB.",
        imageType: "Choose a PNG, JPEG or WebP picture.",
        rateLimited: "You have changed your profile a lot recently. Please try again later.",
        banned: "You cannot change this profile.",
        network: "Could not reach the server. Please try again.",
        generic: "That did not work. Please try again.",
      },
    },
    loadFailed: "Could not load this profile. Please try again in a moment.",
  },
  wallet: {
    connect: "Connect wallet",
    connectTitle: "Connect a wallet",
    privyUnavailable: "Google and email sign-in did not load. You can connect a wallet now, or reload the page to try them again.",
    reload: "Reload",
    noWallet: "No wallet found. Install a browser wallet such as MetaMask, then reload this page.",
    disconnect: "Disconnect",
    login: "Log in",
    logout: "Log out",
    exportKey: "Export key",
    exportKeyHint: "Your key is yours: you can take it to any wallet.",
    switchTo: (chainName: string) => `Switch to ${chainName}`,
    wrongNetwork: (chainName: string) => `Your wallet is on another network. Switch to ${chainName} to continue.`,
    notConfigured: "Trading is not configured for this deployment.",
  },
  trade: {
    buy: "Buy",
    sell: "Sell",
    amountToSpend: (symbol: string) => `Amount to spend (${symbol})`,
    enterIn: (unit: string) => `Enter in ${unit}`,
    youReceive: (amount: string, ticker: string) => `You receive ≈ ${amount} ${ticker}`,
    youReceiveQuote: (amount: string) => `You receive ≈ ${amount}`,
    balanceLabel: "Balance",
    balanceLine: (amount: string) => `Balance ${amount}`,
    amountToSell: (ticker: string) => `Amount to sell (${ticker})`,
    max: "Max",
    breakdown: { price: "Price", fee: "Fee", launchTax: "Launch tax", total: "Total", youReceive: "You receive (est.)", youGet: "You get (est.)", minimum: "Minimum after slippage" },
    slippage: { label: (percent: string) => `Slippage ${percent}%`, custom: "Custom (%)", title: "Slippage tolerance", help: "The most the price may move against you before the trade is refused." },
    insufficientEth: "Not enough ETH for this purchase and network fees.",
    insufficientTokens: "Insufficient token balance",
    stale: "The price has moved. The figures above are being refreshed.",
    bought: (tokens: string, ticker: string, paid: string, symbol: string) => `You bought ${tokens} ${ticker} for ${paid} ${symbol}.`,
    sold: (tokens: string, ticker: string, received: string, symbol: string) => `You sold ${tokens} ${ticker} and received ${received} ${symbol}.`,
    graduating: "GRADUATING…",
    graduatingNote: "This token has filled its curve and is moving to Uniswap. Trading here is paused.",
    approve: {
      step: "Step 1 of 2: approve selling",
      sellStep: "Step 2 of 2: sell",
      explain: "Approve once, and every future sale of this token is a single confirmation. You can limit it to this sale instead.",
      exact: "Approve only this sale",
    },
  },
  session: {
    receiveTitle: "Add ETH to your wallet",
    receiveBody: (symbol: string) => `Send ${symbol} to this address, on the network this app is on. It arrives within a block or so.`,
    menuLabel: "Wallet",
    menuAddress: "Address",
    viewOnExplorer: "View on explorer",
    mainWallet: "Main wallet",
    yourWallet: "Your wallet",
    tradingWallet: "Trading wallet",
    tradingWithThis: "Trading from this wallet",
    balance: "Balance",
    openingTitle: "Opening your trading wallet…",
    needsTitle: "Open your trading wallet",
    needsBody:
      "Your trades are made from a trading wallet, so buying and selling needs no wallet pop-up. Sign one message with your main wallet to open it. It costs nothing, it lives in this browser, and signing the same message on any device opens the same wallet. Only keep small amounts in it.",
    open: "Open trading wallet",
    mismatchTitle: "Your wallet signed differently than before",
    mismatchBody:
      "Your main wallet did not produce the same signature it did when the trading wallet was created, so the trading wallet cannot be recovered here. Nothing has been created or changed, and no funds are lost. Contact support before putting more funds in a trading wallet.",
    topUp: "Deposit",
    topUpTitle: "Deposit ETH to your trading wallet",
    topUpWhy: "A key kept in a browser should not hold your whole balance. 0.1 to 0.3 ETH is plenty for many trades.",
    topUpAmount: "Amount (ETH)",
    topUpSend: "Send from main wallet",
    topUpInsufficient: "Your main wallet does not have enough ETH for this and network fees.",
    toppedUp: (sent: string, now: string) => `Sent ${sent} ETH. Your trading wallet now has ${now} ETH.`,
    withdrawAll: "Withdraw all",
    withdrawTitle: "Withdraw everything to your main wallet",
    withdrawBody: "Sends every token in your trading wallet, then the ETH that is left, to your main wallet. Each transfer is paid for by the trading wallet.",
    withdrawTo: (address: string) => `Destination: ${address}`,
    withdrawRun: "Withdraw everything",
    withdrawDone: (tokens: number, eth: string) => `Sent ${tokens} ${tokens === 1 ? "token" : "tokens"} and ${eth} ETH to your main wallet.`,
    withdrawNothing: "There is nothing left in your trading wallet.",
    withdrawFailed: (count: number) => `${count} ${count === 1 ? "token" : "tokens"} could not be sent and ${count === 1 ? "is" : "are"} still in your trading wallet:`,
    withdrawKeptForRetry: "Your ETH was kept, to pay for another try. Press the button again.",
    withdrawDust: "The ETH left is too small to be worth sending.",
  },
  // What a person is told when a transaction cannot happen. Keyed by the contract's custom error names
  // (docs/02-contract-reference.md); the ones the reference marks internal or admin are deliberately absent.
  tx: {
    generic: "Something went wrong. Please try again.",
    needGas: "You need more ETH for network fees.",
    // One line for both stages: the seam does not tell the panel when the wallet has signed, and a transaction is
    // mined a few seconds later.
    pending: "Confirm in your wallet, then wait for the network…",
    seam: {
      wrong_chain: "Switch your wallet to the right network.",
      not_connected: "Connect a wallet first.",
      no_session: "Your trading wallet is not open yet. Open it, then try again.",
      not_configured: "Trading is not configured for this deployment.",
      reverted: "The transaction failed on chain.",
      bad_amount: "Enter an amount.",
      no_trade_event: "The transaction confirmed, but its result could not be read. Check the block explorer.",
      no_created_event: "The transaction confirmed, but the new token could not be found. Check the block explorer.",
    },
    contract: {
      AlreadyMigrated: "Already on Uniswap.",
      BondingCurveNotSet: "Service not ready.",
      CurveCompleted: "This token has finished its bonding curve and is moving to Uniswap.",
      CurveNotFound: "Unknown token.",
      ERC20InsufficientAllowance: "Approve the token first.",
      ERC20InsufficientBalance: "Insufficient token balance.",
      EthTransferFailed: "ETH transfer failed. Use a wallet that accepts ETH.",
      InsufficientValue: "Not enough ETH sent.",
      InvalidAntiSniperWindow: "Pick one of the allowed windows.",
      NotCompleted: "Not ready to migrate yet.",
      NothingToClaim: "Nothing to claim.",
      PairMismatch: "Migration failed, contact support.",
      QuoteNotEnabled: "This currency is not supported.",
      QuoteNotWeth: "Use the token payment flow for this token.",
      QuoteTransferMismatch: "This currency cannot be used.",
      SafeERC20FailedOperation: "Token transfer failed.",
      SlippageExceeded: "Price changed. Increase slippage or try again.",
      TransferToPairLocked: "Transfers to the pool are locked until the token graduates.",
      ZeroAmount: "Enter an amount.",
    },
  },
  errors: {
    indexing: "Your token is being set up. This page will update in a moment.",
    notFound: "Token not found.",
    pageNotFound: "Page not found.",
    loadFailed: "Could not load this. Please try again in a moment.",
  },
} as const;
